CREATE DATABASE IF NOT EXISTS cohete_skeleton;
USE cohete_skeleton;

CREATE TABLE IF NOT EXISTS todo (
    id CHAR(36) NOT NULL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    completed TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
